Grid:
    GridLayout:
        cols:1
        size:root.width,root.height

        GridLayout:
            cols:2

            Label:
                text: "Nome:"

            TextInput:
                multinline:False

            Label:
                text: "Course: "

            TextInput:
                multinline:False

        Button:
            text: "Enviar"
            on_press: app.btn()