# Generated by Django 4.1 on 2022-12-28 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetodjango',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 20, 10, 23, 133094), verbose_name='Publicado em'),
        ),
    ]
