# Generated by Django 4.1 on 2022-12-30 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_projetodjango_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetodjango',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 22, 33, 59, 140984), verbose_name='Publicado em'),
        ),
    ]
