# Generated by Django 4.1 on 2023-01-02 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_projetodjango_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetodjango',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 23, 1, 4, 702585), verbose_name='Publicado em'),
        ),
    ]
