# Generated by Django 4.1.1 on 2022-09-07 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('ano', models.CharField(max_length=4)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 32, 31, 395874), verbose_name='Publicado em')),
            ],
        ),
    ]
